name: TeamTimeCraft
version: '1.0-SNAPSHOT'
main: me.jose.teamTimeCraft.TeamTimeCraft
api-version: '1.21'

commands:
  playtime:
    description: Vê o tempo jogado de um jogador
    usage: /playtime
  allplaytime:
    description: Vê o tempo de todos os jogadores
    usage: /allplaytime
    permission: op