name: TeamTimeCraft
version: '1.0-SNAPSHOT'
main: me.jose.teamTimeCraft.TeamTimeCraft
api-version: '1.21'

commands:
  playtime:
    description: View the playtime of a player
    usage: /playtime [player]

permissions:
  teamtimecraft.view.others:
    default: op